name: Upload to CurseForge

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip
        run: |
          mkdir AdiBags_Fishing
          cp *.lua *.toc AdiBags_Fishing/
          zip -r AdiBags_Fishing.zip AdiBags_Fishing

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: "${{ secrets.ADIBAGS_FISHING }}"
          project_id: "269672"
          game_endpoint: "wow"
          file_path: "AdiBags_Fishing.zip"
          game_versions: "12.0.5"
          release_type: "release"
          display_name: "AdiBags_Fishing - ${{ github.event.head_commit.timestamp }}"
          changelog: "${{ github.event.head_commit.message }}"
          changelog_type: "markdown"